# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Presidential Rank"
email: hi@crishernandez.co
description: "An experimental Chilean presidential ranking for 2017 election, using Twitter Data."
baseurl: "" # the subpath of your site, e.g. /blog
# url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: crishernandezco
github_username:  crishernandezmaps

# Build settings
markdown: kramdown
